import { useEffect, useState } from "react";
import { compareRuns, getRuns } from "../api/client";
import Page from "./_Page";

export default function Compare() {
  const [runs, setRuns] = useState<any[]>([]); const [first, setFirst] = useState("sample"); const [second, setSecond] = useState("internship"); const [result, setResult] = useState<any>(null); const [error, setError] = useState("");
  useEffect(() => { getRuns().then((data) => setRuns(data.runs || [])).catch(() => setError("Unable to load research runs.")); }, []);
  async function compare() { setError(""); try { setResult(await compareRuns([first, second])); } catch (requestError: any) { setError(requestError.response?.data?.message || "Unable to compare the selected datasets."); } }
  const options = [{ value: "sample", label: "Built-in sample" }, { value: "internship", label: "Documented internship" }, ...runs.map((run) => ({ value: run.run_id, label: run.run_id }))];
  return <Page kicker="Compare datasets" title="Put research results side by side" lede="Compare documented runs without collapsing the assumptions behind each result."><div className="card"><div className="row"><label className="field">First dataset<select value={first} onChange={(event) => setFirst(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="field">Second dataset<select value={second} onChange={(event) => setSecond(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><button className="btn" onClick={compare}>Compare</button></div></div>{error && <p className="error" style={{ marginTop: 12 }}>{error}</p>}{result?.comparisons ? <div className="table-wrap" style={{ marginTop: 16 }}><table><thead><tr><th>Dataset</th><th>P&amp;L</th><th>Drawdown</th><th>Trades</th><th>Win rate</th></tr></thead><tbody>{result.comparisons.map((row: any) => <tr key={row.dataset_label}><td>{row.dataset_label}</td><td>{row.total_pnl ?? "—"}</td><td>{row.max_drawdown ?? "—"}</td><td>{row.trade_count ?? "—"}</td><td>{row.win_rate_pct ? `${row.win_rate_pct.toFixed(2)}%` : "—"}</td></tr>)}</tbody></table></div> : <div className="callout" style={{ marginTop: 16 }}>Select two datasets and compare their metrics, periods, and data sources.</div>}</Page>;
}